### ISSUE TITLE
How to use the FilterPredicate ?

### ISSUE THREAD

**Issue by prsolucoes** [AFNetworking/AFNetworkActivityLogger#30]
Hi,

How to use the FilterPredicate ?

I want discard everything with domains "abc.com" and "xyz.com". 

Can anyone help me?

```
[AFNetworkActivityLogger sharedLogger].filterPredicate = ???
```

**Comment by Lcccocoa** [comment]
NSPredicate *pred = [NSPredicate predicateWithFormat:@"%K = %@",@"URL.host",@"www.baidu.com"];
    [[AFNetworkActivityLogger sharedLogger] setFilterPredicate:pred];
