### ISSUE TITLE
Request body is nil

### ISSUE THREAD

**Issue by Cyclic** [AFNetworking/AFNetworkActivityLogger#31]
I am using the following code to form up a request, and then have the ActivityLogger set to debug level. When I send the request, the activity logger always shows the body as nil. Here is the code:

``` objective-c
    NSMutableURLRequest *request = [self.requestSerializer multipartFormRequestWithMethod:@"PUT"
                                                                                URLString:urlString
                                                                               parameters:params
                                                                constructingBodyWithBlock: ^(id < AFMultipartFormData > formData) {
        [formData appendPartWithFileData:imageData name:@"upload"
                                fileName:[NSString stringWithFormat:@"%@.jpg", params[@"id"]] mimeType:@"image/jpeg"];
    } error:nil];
```

In the activity logger source, the body is always nil:

``` objective-c
    NSString *body = nil;
    if ([request HTTPBody]) {
        body = [[NSString alloc] initWithData:[request HTTPBody] encoding:NSUTF8StringEncoding];
    }
```

The parameters are not null, and the image post completes successfully.
<img width="863" alt="params" src="https://cloud.githubusercontent.com/assets/553800/8840419/b595b700-3095-11e5-9af1-2ef614ea819f.png">

**Comment by SlaunchaMan** [comment]
Looks like you’re trying to make a UTF-8 `NSString` out of a body that is comprised of image data. I wouldn’t expect that that would work; is the `[request HTTPBody]` call returning a valid `NSData` instance?

**Comment by SlaunchaMan** [comment]
Closing this as it’s old, but feel free to re-open if this reoccurs.
