### ISSUE TITLE
NSTimeInterval elapsedTime is nan sometimes

### ISSUE THREAD

**Issue by ppaulojr** [AFNetworking/AFNetworkActivityLogger#35]
Sometimes I get `NSTimeInterval elapsedTime` as `nan`.

To check, set a conditional breakpoint at: https://github.com/AFNetworking/AFNetworkActivityLogger/blob/master/AFNetworkActivityLogger/AFNetworkActivityLogger.m#L165

With condition `elapsedTime != elapsedTime` (check for `nan`)

You'll notice that `objc_getAssociatedObject(notification.object, AFNetworkRequestStartDate)` is returning `nil`

**Comment by yuningalexliu** [comment]
+1

**Comment by ilyannn** [comment]
Yup, I always get it for some reason :)
`objc_getAssociatedObject(notification.object, AFNetworkRequestStartDate)` is always nil for me.

**Comment by cameronehrlich** [comment]
To handle checking for `nan`, try this:
```objective-c
#include <math.h>

if (isnan(elapsedTime)) {
     elapsedTime = 0.0f;
}
```

**Comment by SlaunchaMan** [comment]
Hi Pedro and others! I’m going to close this as it’s over a year old, but if you still experience this under 3.0.0, please re-open it and let me know!
