### ISSUE TITLE
AFNetworking 3 support

### ISSUE THREAD

**Issue by getaaron** [AFNetworking/AFNetworkActivityLogger#40]
Can we update this to support AFNetworking 3?

**Comment by Zeropointer11** [comment]
yes please uptadte it to AFNetworking 3

**Comment by vkrikun** [comment]
yes, would be really cool to have it  for AFNetworking 3.

**Comment by XabierGoros** [comment]
I join to the request too  :)

**Comment by semerda** [comment]
Ditto!

**Comment by ClearerMe** [comment]
Do it !!! @getaaron

**Comment by electic** [comment]
Just do it :)

**Comment by mthuong** [comment]
Let's do it 🎯

**Comment by AWrightIV** [comment]
This is a duplicate thread. Please see https://github.com/AFNetworking/AFNetworkActivityLogger/issues/34 for further information.

**Comment by getaaron** [comment]
Closing as a dupe of https://github.com/AFNetworking/AFNetworkActivityLogger/issues/34
