### ISSUE TITLE
Carthage for 3_0_0 branch

### ISSUE THREAD

**Issue by kingtai** [AFNetworking/AFNetworkActivityLogger#41]
May i know why i cant get the 3_0_0 branch by carthage?
I am importing it by the cartfile adding
github "AFNetworking/AFNetworkActivityLogger" "3_0_0"

but the below error found
The following build commands failed:
    PhaseScriptExecution Run\ Script /Users/kt/Library/Developer/Xcode/DerivedData/AFNetworkActivityLogger-helhhbodwgykeqcmbxpfeotwtokk/Build/Intermediates/AFNetworkActivityLogger.build/Release-iphoneos/AFNetworkActivityLogger\ iOS.build/Script-29D96E771BCC36E700F571A5.sh
(1 failure)

The branch should be here but cannot get it ?
Is there any mistake in my cartfile?
Many thanks!

**Comment by Zeropointer11** [comment]
i have the same Issue i have found that the problem was the RunScript in the Build Phases

in the Shell Line should be: /bin/sh
and in the Field below: /usr/local/bin/carthage copy-frameworks

pleas fix this every carthage update will overwrite my changes

**Comment by rbaumbach** [comment]
If anybody is interested, I just forked the repo and created version 3.0.0 that is Carthage compatible.

**Comment by SlaunchaMan** [comment]
The 3.0.0 release is imminent, so Carthage should work moving forward. Once the release is done let me know if there are any issues!
