### ISSUE TITLE
App crash with version 3.0.0

### ISSUE THREAD

**Issue by renatosarro** [AFNetworking/AFNetworkActivityLogger#44]
Hi,
I'm with problem when I started the AFNetworkActivityLogger. When init the AFNetworkActivityConsoleLogger I received the message:

**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[AFNetworkActivityLogger loggers]: unrecognized selector sent to instance 0x7fd392e6d060'

My code is:

``` objc
AFNetworkActivityConsoleLogger *logger = [AFNetworkActivityLogger sharedLogger].loggers.anyObject;
        logger.level = AFLoggerLevelDebug;
[[AFNetworkActivityLogger sharedLogger] addLogger:logger];   
[[AFNetworkActivityLogger sharedLogger] startLogging];
```

**Comment by SlaunchaMan** [comment]
I’m closing out old issues on this project, but if you still need help, feel free to ask on StackOverflow—and if you still get a crash, feel free to reopen this issue.
