### ISSUE TITLE
carthage

### ISSUE THREAD

**Issue by lizhihui0215** [AFNetworking/AFNetworkActivityLogger#46]
how to use carthage?

when I have add `github "AFNetworking/AFNetworkActivityLogger" "3_0_0"` in mine carthage file
then run `carthage update` in the command get this error

The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/lizhihui/Library/Developer/Xcode/DerivedData/AFNetworkActivityLogger-ggidisnayfprzedgumpirqxiaxzz/Build/Intermediates/AFNetworkActivityLogger.build/Release-iphoneos/AFNetworkActivityLogger\ iOS.build/Script-29D96E771BCC36E700F571A5.sh
(1 failure)

**Comment by rbaumbach** [comment]
It doesn't look like there is any rush on getting a version 3 of this using Carthage any time soon.

If you are interested, I just forked the repo and created version 3.0.0 that is Carthage compatible.  You can add it like so:

`github "rbaumbach/AFNetworkActivityLogger" == 3.0.0`

**Comment by SlaunchaMan** [comment]
The 3.0.0 tag is now live, so Carthage should work as expected. Feel free to reopen this issue if that’s not the case!
