### ISSUE TITLE
AFNetworkActivityLogger, source of deadlock?

### ISSUE THREAD

**Issue by troypayne** [AFNetworking/AFNetworkActivityLogger#47]
I've been dealing with my app locking up when I make a lot of asynchronous remote requests. I'm using a combination of ReactiveCocoa and AFNetworking. For a week I've been trying to figure it out.

I've now traced it back to AFNetworkActivityLogger, I think at least, because when I comment it out, it doesn't deadlock anymore.

//[[AFNetworkActivityLogger sharedLogger] startLogging];

I'm using the latest version from cocoapods:
Using AFNetworkActivityLogger (2.0.4) 

Here's what my stack trace looks like while my app is frozen and when I enable a symbolic breakpoint on __psynch_mutexwait

<img width="543" alt="screen shot 2017-03-21 at 6 34 06 pm" src="https://cloud.githubusercontent.com/assets/3412692/24174105/579fc280-0e65-11e7-931c-383342ed4875.png">

**Comment by SlaunchaMan** [comment]
Hi Troy! I’m going to close this for now since it’s almost a year old, but now that we have a new release, if you still experience this, feel free to re-open it!
