### ISSUE TITLE
Latest Release 3.0.0 is not working with AFNetworking 3.1

### ISSUE THREAD

**Issue by pradnya-nikam** [AFNetworking/AFNetworkActivityLogger#49]
Was using below hack to support `AFNetworking 3.1`, but is doesn't work anymore as 3.0.0 branch was merged 2 days ago!

`pod 'AFNetworkActivityLogger', git: 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', branch: '3_0_0'
`
Tried to fix it by doing  
`pod 'AFNetworkActivityLogger', '3.0.0'
`
but doesn't work..

Also tried to change podfile by removing the version but that is defaulting to AFNetworkingActivityLogger version `2.0.1` which starts throwing incompatibility errors.

**Comment by JatinPreetSingh** [comment]
The only possibles solution for now is to reinstall pods while commenting AFNetworkActivityLogger and than add manullay files of  AFNetworkActivityLogger in the project

**Comment by lukkob** [comment]
Just remove `branch: '3_0_0'` and it should be alright

`pod 'AFNetworkActivityLogger', git: 'https://github.com/AFNetworking/AFNetworkActivityLogger.git'`

**Comment by carol-mohemian** [comment]
One fix would be to update the .podspec on cocoapods? 🤔 (from maintainer side I mean)

**Comment by ghost** [comment]
Seems like the new 3.0.0 release is not yet available on [cocoapods.org](https://cocoapods.org/pods/AFNetworkActivityLogger). In the meantime using `pod 'AFNetworkActivityLogger', git: 'https://github.com/AFNetworking/AFNetworkActivityLogger.git', branch: 'master'` as pointed out above works for us.

**Comment by ashislaha** [comment]
Thanks @lukkob, it's working after removing branch: '3_0_0'.

**Comment by SlaunchaMan** [comment]
Sorry about that, I deleted the branch out of habit when merging the PR. I've restored that branch, and this has also been released on CocoaPods!
