### ISSUE TITLE
Dependency to AFNetworking 4.0.0

### ISSUE THREAD

**Issue by ajanuar** [AFNetworking/AFNetworkActivityLogger#59]
AFNetworking has been updated to 4.0.0 to replace UIWebView with WKWebView. Using current latest `AFNetworkActivityLogger` and `AFNetworking (= 4.0.0)` will have confict.

**Comment by datkinnguyen** [comment]
@ajanuar I had the same issue. I ended up forking this repo and just updated podspec to point to AFNetworking 4.0, and it works well. If you are in a rush then maybe that's something you can do while waiting for official release.

**Comment by mahi8813** [comment]
> @ajanuar I had the same issue. I ended up forking this repo and just updated podspec to point to AFNetworking 4.0, and it works well. If you are in a rush then maybe that's something you can do while waiting for official release.

Awesome, We have the same requirement. We will try your solution
